# Generated by Django 3.2.3 on 2021-08-31 06:04

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BilimSoxasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='JurnalTur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Jurnal yillari',
            },
        ),
        migrations.CreateModel(
            name='KasbVaMutaxasislik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='images/')),
                ('definition', models.TextField(max_length=200)),
                ('prof_stand', models.FileField(blank=True, default=None, null=True, upload_to='files/')),
                ('malaka_talab', models.FileField(blank=True, default=None, null=True, upload_to='files/')),
                ('uquv_reja', models.FileField(blank=True, default=None, null=True, upload_to='files/')),
                ('uquv_dastur', models.FileField(blank=True, default=None, null=True, upload_to='files/')),
                ('uqutish_mater', models.FileField(blank=True, default=None, null=True, upload_to='files/')),
                ('professiog', models.FileField(blank=True, default=None, null=True, upload_to='files/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Muhokama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='images/')),
                ('definition', models.TextField(max_length=200)),
                ('prof_stand', models.FileField(blank=True, default=None, null=True, upload_to='files/')),
                ('malaka_talab', models.FileField(blank=True, default=None, null=True, upload_to='files/')),
                ('uquv_reja', models.FileField(blank=True, default=None, null=True, upload_to='files/')),
                ('uquv_dastur', models.FileField(blank=True, default=None, null=True, upload_to='files/')),
                ('uqutish_mater', models.FileField(blank=True, default=None, null=True, upload_to='files/')),
                ('professiog', models.FileField(blank=True, default=None, null=True, upload_to='files/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QisqaKursTur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Qisqa muddatli kurslar turi',
            },
        ),
        migrations.CreateModel(
            name='SizUchunFoydali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('url', models.URLField(verbose_name='url')),
                ('imag', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TalimSoxasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('bilim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.bilimsoxasi')),
            ],
            options={
                'db_table': "Ta'lim soxasi",
            },
        ),
        migrations.CreateModel(
            name='Yangilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('img', models.ImageField(upload_to='images/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='UquvQullanma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('definition', models.TextField(max_length=200)),
                ('prof_stand', models.FileField(blank=True, default=None, null=True, upload_to='files/')),
                ('guv_img', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('guv_nomer', models.CharField(max_length=10)),
                ('guv_date', models.DateField(auto_now=True)),
                ('guv_muall', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('date', models.DateField(auto_now_add=True)),
                ('k_va_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.kasbvamutaxasislik')),
                ('tSoxa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.talimsoxasi')),
            ],
        ),
        migrations.CreateModel(
            name='UquvMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('definition', models.TextField(max_length=200)),
                ('prof_stand', models.FileField(blank=True, default=None, null=True, upload_to='files/')),
                ('guv_img', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('guv_nomer', models.CharField(max_length=10)),
                ('guv_date', models.DateField(auto_now=True)),
                ('guv_muall', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('date', models.DateField(auto_now_add=True)),
                ('tSoxa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.talimsoxasi')),
            ],
        ),
        migrations.CreateModel(
            name='TalimYunalishi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tSoxa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.talimsoxasi')),
            ],
        ),
        migrations.CreateModel(
            name='QisqaMuddatliKurslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('name', models.CharField(max_length=200)),
                ('difinition', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('pdf', models.FileField(blank=True, default=None, null=True, upload_to='files/')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, default=None, null=True, verbose_name='YouTube URL')),
                ('date', models.DateField(auto_now_add=True)),
                ('kurs_tur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.qisqakurstur')),
            ],
        ),
        migrations.AddField(
            model_name='kasbvamutaxasislik',
            name='tYunalish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.talimyunalishi'),
        ),
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.CharField(max_length=10)),
                ('pdf', models.FileField(upload_to='files/')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.jurnaltur')),
            ],
        ),
    ]
