# Generated by Django 3.2.3 on 2021-08-22 17:38

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qisqamuddatlikurslar',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=None, null=True, verbose_name='YouTube URL'),
        ),
    ]
