# Generated by Django 3.2.3 on 2021-08-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_qisqamuddatlikurslar_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qisqamuddatlikurslar',
            name='_id',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='qisqamuddatlikurslar',
            name='difinition',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='qisqamuddatlikurslar',
            name='pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files/'),
        ),
    ]
