# Generated by Django 3.2.3 on 2021-08-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20210822_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qisqakurstur',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
