# Generated by Django 3.2.3 on 2021-09-06 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_alter_qisqakurstur_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talimsoxasi',
            name='bilim_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilim', to='basic_app.bilimsoxasi'),
        ),
    ]
