# Generated by Django 3.2.3 on 2021-09-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_alter_talimsoxasi_bilim_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kasbvamutaxasislik',
            name='definition',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='muhokama',
            name='definition',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='qisqamuddatlikurslar',
            name='difinition',
            field=models.TextField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='sizuchunfoydali',
            name='description',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='uquvmaterial',
            name='definition',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='uquvqullanma',
            name='definition',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='description',
            field=models.TextField(max_length=512),
        ),
    ]
