# Generated by Django 3.2.6 on 2021-09-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20210911_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uquvmaterial',
            options={'verbose_name': "O'quv material", 'verbose_name_plural': "O'quv materiallar"},
        ),
        migrations.AlterModelOptions(
            name='uquvqullanma',
            options={'verbose_name': "O'quv qo'llanma", 'verbose_name_plural': "O'quv qo'llanmalar"},
        ),
    ]
