# Generated by Django 3.2.6 on 2021-09-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20210914_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasbvamutaxasislik',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uquvmaterial',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uquvqullanma',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kasbvamutaxasislik',
            name='definition',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='muhokama',
            name='definition',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='qisqamuddatlikurslar',
            name='difinition',
            field=models.TextField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='sizuchunfoydali',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='uquvmaterial',
            name='definition',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='uquvqullanma',
            name='definition',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
