# Generated by Django 3.2.6 on 2021-09-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20210921_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kasbvamutaxasislik',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='muhokama',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qisqamuddatlikurslar',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='uquvmaterial',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='uquvqullanma',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
