# Generated by Django 3.2.6 on 2021-10-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_auto_20210928_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasbvamutaxasislik',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='muhokama',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='qisqamuddatlikurslar',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='uquvmaterial',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='uquvqullanma',
            name='slug',
            field=models.SlugField(default=None, null=True),
        ),
    ]
