# Generated by Django 3.2.6 on 2021-10-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_auto_20211012_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kasbvamutaxasislik',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='muhokama',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='qisqamuddatlikurslar',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='uquvmaterial',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='uquvqullanma',
            name='slug',
        ),
    ]
