# Generated by Django 3.2.6 on 2021-11-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_alter_yangilik_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talimyunalishi',
            name='tSoxa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_soxa', to='basic_app.talimsoxasi'),
        ),
        migrations.AlterField(
            model_name='uquvqullanma',
            name='guv_muall',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uquvqullanma',
            name='guv_nomer',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='uquvqullanma',
            name='k_va_m',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.kasbvamutaxasislik', verbose_name='Kasb va mutaxasisliklar'),
        ),
        migrations.AlterField(
            model_name='uquvqullanma',
            name='tSoxa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.talimsoxasi', verbose_name="Ta'lim soxasi"),
        ),
    ]
